### ISSUE TITLE
How Can I put camera in SurfaceView

### ISSUE THREAD

**Issue by habouseif** [Lukieoo/QrBarcode#1]
hey I really liked your code and I just want to ask u , how to load the camera in Surface view, I need tha camera to load or to be open in particular part of the layout , could u help me with this

**Comment by Lukieoo** [comment]
Please check in this library maybe you can find here this solution .
https://github.com/journeyapps/zxing-android-embedded 

this is a similar question : 
https://stackoverflow.com/questions/49104965/using-zxing-barcode-reader-through-surfaceview

https://github.com/dm77/barcodescanner/issues/67

https://stackoverflow.com/questions/40086498/how-to-make-zxing-shown-in-part-of-activity-not-full-screen-in-android

**Comment by habouseif** [comment]
thankss alot!!!
